Fix issue: memory_hot_add_basic: 'current_testcase_name' is undefined at test_rescue
vmware/ansible-vsphere-gos-validation pull request #520
Opened 2023-12-11 01:54 UTC by ZouYuhua

Fix issue: memory_hot_add_basic: 'current_testcase_name' is undefined at test_rescue

2023-11-17 01:56:22,017 | Failed at Play [1_memory_hot_add_basic] ********************
2023-11-17 01:56:22,017 | TASK [1_memory_hot_add_basic][Skip testcase: memory_hot_add_basic, reason: Blocked] 
task path: /home/worker/workspace/Ansible_OracleLinux_9.x_70U1_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/skip_test_case.yml:21
fatal: [localhost]: FAILED! => Test case 'memory_hot_add_basic' is blocked because memory hotadd test value list is empty
error message:
Test case 'memory_hot_add_basic' is blocked because memory hotadd test value list is empty
2023-11-17 01:56:22,017 | TASK [1_memory_hot_add_basic][Print failed test case] ******
task path: /home/worker/workspace/Ansible_OracleLinux_9.x_70U1_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:14
fatal: [localhost]: FAILED! => The task includes an option with an undefined variable. The error was: 'current_testcase_name' is undefined. 'current_testcase_name' is undefined
The error appears to be in '/home/worker/workspace/Ansible_OracleLinux_9.x_70U1_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml': line 14, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: ""Print failed test case""
  ^ here
error message:
The task includes an option with an undefined variable. The error was: 'current_testcase_name' is undefined. 'current_testcase_name' is undefined
The error appears to be in '/home/worker/workspace/Ansible_OracleLinux_9.x_70U1_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml': line 14, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: ""Print failed test case""
  ^ here"

2023-12-11 01:56 UTC, ZouYuhua commented
passed to test the fix:
<img width="588" alt="image" src="https://github.com/vmware/ansible-vsphere-gos-validation/assets/41054978/f29fea75-26b2-4bca-91d4-cdca6a737a72">

2023-12-12 01:23 UTC, keirazhang requested changes

2023-12-12 01:23 UTC, keirazhang commented on common/test_rescue.yml
> +
Please update `linux/memory_hot_add_basic/memory_hot_add_basic.yml` not this file. You should move up `test_setup.yml` to be executed at first.

2023-12-12 02:21 UTC, keirazhang commented on linux/memory_hot_add_basic/memory_hot_add_basic.yml
> +        - include_tasks: ../setup/test_setup.yml
Missing task name.

2023-12-12 07:29 UTC, ZouYuhua commented
@keirazhang 
passed the teting:
![Uploading image.png…]()

2023-12-12 07:31 UTC, keirazhang approved these changes
LGTM. Thanks!

2023-12-12 07:32 UTC, merged