[Pardus] Fix pardus gosc matrix
vmware/ansible-vsphere-gos-validation pull request #553
Opened 2024-02-28 06:22 UTC by ZouYuhua

Task
perl GOSC for Pardus is supported since 8.0U2 and 7.0.3 P08. Therefore, we can skip perl GOSC testing for Pardus on ESXi earlier than those versions.

Testing passed for Pardus 21.x XFCE and 23.1 XFCE.
Testing is on-going for Pardus 21.x Server and 23.1 Server.

2024-02-28 07:20 UTC, keirazhang requested changes

2024-02-28 07:20 UTC, keirazhang commented on linux/guest_customization/gosc_support_matrix.yml
> +      8.0.1: N/A
7.0.3 build should be 22357613, and you should add one more line of 8.0.2 GA build after 8.0.1.

2024-02-28 07:20 UTC, keirazhang commented on linux/guest_customization/gosc_support_matrix.yml
> +      8.0.1: N/A
7.0.3 build should be 22357613, and you should add one more line of 8.0.2 GA build after 8.0.1.

2024-02-28 07:23 UTC, keirazhang commented on linux/guest_customization/gosc_support_matrix.yml
> +  '21.0':
This project supports Pardus since 21.2, so it is better to change the start version to 21.2

2024-02-29 07:24 UTC, ZouYuhua commented
Hi Qi,
Testing passed for Pardus 21.x XFCE and 23.1 XFCE.
Testing is done for pardus 21.x Server and 23.1 Server. The test result is expected.

Please help review the code. Thanks.

2024-02-29 09:49 UTC, keirazhang commented on linux/guest_customization/gosc_support_matrix.yml
> +
Please remove empty lines 119 ~ 122.

2024-03-01 03:24 UTC, keirazhang approved these changes
LGTM. Thanks!

2024-03-01 03:35 UTC, merged